# preload = ~/dotfiles/wallpapers/wall2.png
# wallpaper = , ~/dotfiles/wallpapers/wall2.png

# preload = $HOME/dotfiles/wallpapers/wall2.png
# wallpaper = , $HOME/dotfiles/wallpapers/wall2.png
#
# splash = true

wallpaper {
  monitor = HDMI-A-1
  path = $HOME/dotfiles/wallpapers/wall2.png
  fit_mode = cover
}

wallpaper {
  monitor = DP-3
  path = $HOME/dotfiles/wallpapers/wall2.png
  fit_mode = cover
}

