return {
  ensure_installed = {
    "go",
    "gomod",
    "gosum",
    "gowork",
    "gotmpl",
    "lua",
    "pkl",
    "rust",
    "gleam",
    "templ",
    "hyprlang",
    "vim",
    "vimdoc",
    "python",
    "dockerfile",
    "bash",
    "json",
    "yaml",
    "typescript",
    "javascript",
    "tsx",
    "css",
  },
  highlight = {
    enable = true,
    use_languagetree = true,
  },
  indent = { enable = true },
  autotag = {
    enable = true,
    enable_rename = true,
    enable_close = true,
    enable_close_on_slash = true,
    filetypes = { "html", "xml" },
  },
}
